## Principal Component Analysis Implementation

In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

In [7]:
dataset = load_iris()
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
X = dataset['data']
y = dataset['target']

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y ,test_size=0.33, random_state=21)

In [15]:
x_train.shape

(100, 4)

In [16]:
y_train.shape

(100,)

In [17]:
x_test

array([[5.8, 2.6, 4. , 1.2],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.7, 3. , 4.2, 1.2],
       [6.6, 3. , 4.4, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.8, 1.5, 0.3],
       [5.5, 2.4, 3.7, 1. ],
       [5.6, 3. , 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.7, 3. , 5. , 1.7],
       [6. , 3. , 4.8, 1.8],
       [6.1, 2.8, 4.7, 1.2],
       [5.8, 4. , 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 2.7, 4.9, 1.8],
       [6. , 2.2, 4. , 1. ],
       [6. , 2.7, 5.1, 1.6],
       [6.4, 2.9, 4.3, 1.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.5, 1.3, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [6.3, 2.3, 4.4, 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [7.9, 3.8, 6.4, 2. ],
       [5.9, 3.2, 4.8, 1.8],
       [5.1, 3.8, 1.6, 0.2],
       [6.2, 2

In [18]:
x_test.shape

(50, 4)

In [19]:
y_test.shape

(50,)

In [21]:
pca =PCA(n_components=3)

In [22]:
pca

,n_components,3
,copy,True
,whiten,False
,svd_solver,'auto'
,tol,0.0
,iterated_power,'auto'
,n_oversamples,10
,power_iteration_normalizer,'auto'
,random_state,None


In [23]:
x_train = pca.fit_transform(x_train)

In [24]:
x_train

array([[ 1.37928907e+00,  4.98057388e-01, -2.94660327e-01],
       [-2.79008046e+00,  9.34493677e-02, -9.28814528e-02],
       [ 8.42827758e-01,  4.65184976e-01, -2.67345840e-01],
       [ 3.71250960e+00,  2.61575408e-01, -4.48942958e-01],
       [ 5.53707539e-01, -4.47963025e-01,  2.70389905e-02],
       [ 1.51066560e-01, -3.52170022e-01, -2.82293895e-01],
       [-2.83292548e+00, -3.41382376e-01,  4.85941343e-03],
       [-2.73626201e+00,  2.95736321e-01,  3.26656496e-02],
       [ 2.99163566e+00,  6.98580481e-01, -2.42134986e-01],
       [-2.71985486e+00, -2.22997570e-01,  1.37326748e-02],
       [-2.59442280e+00,  6.26920278e-01, -6.73317160e-02],
       [-3.30630989e+00,  1.04987823e-01,  2.79941559e-01],
       [-2.97647967e+00, -1.63065885e-01,  3.78936625e-03],
       [-2.49616753e+00,  4.08286058e-01, -1.19009488e-01],
       [ 2.87947452e-01, -3.18734528e-01,  7.54265473e-02],
       [ 8.00767811e-02, -6.94097764e-01, -5.89817061e-02],
       [-2.64948083e+00,  3.50196208e-01

In [25]:
x_test = pca.transform(x_test)

In [26]:
pca.components_

array([[ 0.36664295, -0.09135281,  0.85541602,  0.35424716],
       [ 0.69065223,  0.69296811, -0.19977228, -0.05371893],
       [-0.5277204 ,  0.58330865,  0.03314436,  0.61657412]])

In [27]:
pca.explained_variance_ratio_

array([0.93174616, 0.04844162, 0.01519584])