## Perceptron

#### The Perceptron
###### Its the simplest ANN architecture. it was invented by Frank Rosenbiatt in 1957 and published as Tosenblatt,

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use('fivethirtyeight')

In [3]:
class perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f'self.weights: {self.weights}')
        self.eta = eta
        self.epochs = epochs
    
    def activationFunction(self, inputs,weights):
        z = np.dot(inputs,weights)
        return np.where(z>0,1,0)

    def fit(self,x,y):
        self.x = x
        self.y = y

        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]   #conctination
        print(f'x_with_bias :\n{x_with_bias}')
        for epoch in range(self.epochs):
            print(f'for epoch: {self.epochs}')
            y_hat = self.activationFunction(x_with_bias, self.weights)
            print(f'prediction value: \n{y_hat}')
            error = self.y - y_hat
            print(f'error:\n{error}')
            self.weights = self.weights + self.eta*np.dot(x_with_bias.T, error)
            print(f'updated weights: \n {self.weights}')
            print('##############')


    def predict(self,x):
        x_with_bias = np.c_[x, -np.ones((len(self.x),1))] 
        return self.activationFunction(x_with_bias, self.weights)

#### AND Operation:

In [4]:
data = {'x1':[0,0,1,1], 'x2':[0,1,0,1],'y':[0,0,0,1]}
AND = pd.DataFrame(data)
AND

,x1,x2,y
0,0,0,0
1,0,1,0
2,1,0,0
3,1,1,1


In [5]:
x = AND.drop('y',axis=1)
x

,x1,x2
0,0,0
1,0,1
2,1,0
3,1,1


In [6]:
y = AND['y']
y.to_frame()

,y
0,0
1,0
2,0
3,1


In [7]:
model = perceptron(eta= 0.5, epochs=10)
model.fit(x,y)

self.weights: [-3.22241203e-05 -1.00424473e-04 -1.22426089e-04]
x_with_bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 10
prediction value: 
[1 1 1 0]
error:
0   -1
1   -1
2   -1
3    1
Name: y, dtype: int64
updated weights: 
 [-3.22241203e-05 -1.00424473e-04  9.99877574e-01]
##############
for epoch: 10
prediction value: 
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [0.49996778 0.49989958 0.49987757]
##############
for epoch: 10
prediction value: 
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
 [-3.22241203e-05 -1.00424473e-04  1.49987757e+00]
##############
for epoch: 10
prediction value: 
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [0.49996778 0.49989958 0.99987757]
##############
for epoch: 10
prediction value: 
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [0.99996778 0.99989958 0.49987757]
#

In [8]:
model.predict(x)

array([0, 0, 0, 1])

In [9]:
model.weights

array([0.99996778, 0.99989958, 1.49987757])

### OR Operator


In [10]:
data = {'x1':[0,0,1,1], 'x2':[0,1,0,1],'y':[0,1,1,1]}
OR = pd.DataFrame(data)
OR

,x1,x2,y
0,0,0,0
1,0,1,1
2,1,0,1
3,1,1,1


In [11]:
x = OR.drop('y',axis=1)
x

,x1,x2
0,0,0
1,0,1
2,1,0
3,1,1


In [12]:
y = OR['y']
y.to_frame()

,y
0,0
1,1
2,1
3,1


In [13]:
model = perceptron(eta= 0.5, epochs=10)
model.fit(x,y)

self.weights: [ 1.15303500e-04 -1.18937771e-04  8.18928679e-05]
x_with_bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 10
prediction value: 
[0 0 1 0]
error:
0    0
1    1
2    0
3    1
Name: y, dtype: int64
updated weights: 
 [ 0.5001153   0.99988106 -0.99991811]
##############
for epoch: 10
prediction value: 
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
 [ 0.5001153   0.99988106 -0.49991811]
##############
for epoch: 10
prediction value: 
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
 [5.00115304e-01 9.99881062e-01 8.18928679e-05]
##############
for epoch: 10
prediction value: 
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
 [5.00115304e-01 9.99881062e-01 8.18928679e-05]
##############
for epoch: 10
prediction value: 
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
 [5.00115304e-01 9.99881062e-01 8.189